name: transports
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  # Core Math & Data
  - numpy>=1.26
  - pandas>=2.2
  - xarray>=2025.12.0
  - xgcm>=0.9.0
  - dask>=2025.10.0
  # IO Backends
  - netcdf4
  - h5netcdf
  - zarr
  # Performance Boosters
  - bottleneck
  - numbagg
  # Visualization
  - matplotlib>=3.10
  - cartopy>=0.25.0
  - nc-time-axis>=1.4.0
  - pip:
    - sectionate
    - regionate
